### ISSUE TITLE
Allow Force Creation of Resource Group in New-Test-Resources.ps1

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk#1042]
Update the resource creation PowerShell script to always create the resource group to allow test suites that create their own resources to hook into Resource Group build up and tear down that the pipeline templates offer.

**Comment by danieljurek** [comment]
@heaths -- We found an interesting workaround here but I think a parameter for `New-TestResources.ps1` might be a good idea here... 

The invocation might look something like this

tests.yml

```yml
trigger: none

jobs:
  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
    parameters:
      ResourceProvisionerParams: '-AlwaysCreateResourceGroup'  # Extra parameters specified here
      ServiceDirectory: search
      Timeout: 120
       ...
```

archetype-sdk-tests.yml

```yml
...
        - pwsh: >-
            eng/New-TestResources.ps1
            -BaseName $(BaseName)
            -ServiceDirectory ${{ parameters.ServiceDirectory }}
            -TestApplicationId '$(aad-azure-sdk-test-client-id)'
            -TestApplicationSecret '$(aad-azure-sdk-test-client-secret)'
            -TestApplicationOid '$(aad-azure-sdk-test-client-oid)'
            -TenantId '$(aad-azure-sdk-test-tenant-id)'
            -ProvisionerApplicationId '$(provisioner-aad-id)'
            -ProvisionerApplicationSecret '$(provisioner-aad-secret)'
            -DeleteAfterHours 24
            -CI
            -Force
            -Verbose
            ${{ parameters.ResourceProvisionerParams }}   # Extra parameters inserted inline
          displayName: Provision Test Resources
      - ${{ parameters.PreRunSteps }}

...

```
