### ISSUE TITLE
Migrate environment namespaced pipeline variables to subscription configuration

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk#2075]
Some environment variables used in our live tests use azure pipelines variable references to load secret values. In our move to support sovereign cloud testing, we would need to support switching the variable name reference based on the environment. We are designing the pipeline live test templates in a way that aims to eliminate the need for such switching, in favor of keeping all cloud specific values (secret or not) in one subscription configuration. As a result, we need to consolidate the different azure pipelines secret variables into the subscription configuration, and refer to them by a single name.

Example from the [identity live test yaml](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/tests.yml#L45)
```
    EnvVars:
      AZURE_IDENTITY_TEST_TENANTID: $(net-identity-tenantid)
      AZURE_IDENTITY_TEST_USERNAME: $(net-identity-username)
      AZURE_IDENTITY_TEST_PASSWORD: $(net-identity-password)
      IDENTITY_SP_CLIENT_ID: $(net-identity-sp-clientid)
      IDENTITY_SP_TENANT_ID: $(net-identity-sp-tenantid)
```

So instead of the need for `$(net-identity-sp-clientid-gov)`, we can move the value into $(sub-config-azure-gov-test-resources), like so:

```
  {
   ...
  "EnvironmentVariables": {
        "net-identity-sp-cert": <value>
    },
    ...
}
```
