### ISSUE TITLE
[Feature request] Deploy test resources close to Mac Agent location

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk#2791]
Since we introduced Mac Agents I can see test run deterioration with Mac Agents being the tail.

Here are some thoughts:
- We deploy storage test resources in certain region due to feature availability, but I think we can workaround this by testing N-1 service version on Macs, so that latest features tests just don't run
- We should detect where Mac agents we got is located and pick Azure DC that's nearby

Here's some evidence from .NET and Java pipelines:
![image](https://user-images.githubusercontent.com/61715331/116604917-a1c4bd80-a8e3-11eb-99e7-f0c8e77b5e46.png)
![image](https://user-images.githubusercontent.com/61715331/116604927-a4271780-a8e3-11eb-93bf-6df613525644.png)

**Comment by benbp** [comment]
FYI @kurtzeborn @mitchdenny

**Comment by mitchdenny** [comment]
The region that Macs get deployed in will probably be fairly static so you could potentially push your test resources over to that region. @benbp how much effort would it be to pass in a matrix value to overrides the location for test resource creation for just macOS legs?

Ideally we can do a quick test just to validate whether the changed region does indeed help performance as there are potentially other contributing factors that we should rule out (e.g. optimization issues for macOS). I believe that the underlying Mac provider has points of presence in Silicon Valley, Vegas and Atlanta. I think we are probably using agents in the valley, so perhaps deploying the resources in West US 2?

**Comment by kasobol-msft** [comment]
If that were true I'd expect lower variance, i.e. these locations all seem far away from Canada Central region.
For example here https://dev.azure.com/azure-sdk/internal/_build/results?buildId=872600&view=results
![image](https://user-images.githubusercontent.com/61715331/116897542-3718c800-abea-11eb-9ef0-3677aeb8a690.png)

Might be worth injecting some script into pipelines to collect data that can be used to determine where Macs are and what's the latency to test resources.

**Comment by mitchdenny** [comment]
These Mac's aren't on the Azure infrastructure, so the network performance could vary quite a bit from what you might expect say from a VM running inside West US.

**Comment by benbp** [comment]
@mitchdenny we would need to plumb location in from the matrix (done only via CloudConfig right now) as well as support conditional replace (e.g. where field A == <query>, replace field B).

I think the easiest way to do it right now would be to define it as another CloudConfig entry:

```
parameters:
  CloudConfig:
    Public:
      SubscriptionConfiguration: $( ... )
      Location: canadacentral
      MatrixFilters:
        - OSVmImage=^(?!.*macOS).*
    MacOSCanada:
      SubscriptionConfiguration: $( ... )
      Location: westus2
      MatrixFilters:
        - OSVmImage=.*macOS.*
```
