### ISSUE TITLE
Automate Pod Identity testing

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk#814]
# Pod Identity is now deprecated
https://github.com/Azure/aad-pod-identity#aad-pod-identity-deprecated

use workload identity instead

--------------------

We need to automate testing our identity libraries' managed identity implementations with pod identity (AKS).

Below are instructions for manually testing Python's implementation ([as seen in the repo](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity/tests/pod-identity)):

# Testing managed identity in Azure Kubernetes Service

# prerequisite tools
- Azure CLI
  - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
- Docker CLI
  - https://hub.docker.com/search?q=&type=edition&offering=community
- Helm 2.x (3.x doesn't handle CRDs properly at time of writing)
  - https://github.com/helm/helm/releases

# Azure resources
This test requires instances of these Azure resources:
- Azure Key Vault
- Azure Managed Identity
  - with secrets/set and secrets/delete permission for the Key Vault
- Azure Container Registry
- Azure Kubernetes Service
  - RBAC requires additional configuration not provided here, so an RBAC-disabled cluster is preferable
  - the cluster's service principal must have 'Managed Identity Operator' role over the managed identity
  - must be able to pull from the Container Registry

The rest of this section is a walkthrough of deploying these resources.

### set environment variables to simplify copy-pasting
- RESOURCE_GROUP
  - name of an Azure resource group
  - must be unique in the Azure subscription
  - e.g. 'pod-identity-test'
- AKS_NAME
  - name of an Azure Kubernetes Service
  - must be unique in the resource group
  - e.g. 'pod-identity-test'
- ACR_NAME
  - name of an Azure Container Registry
  - 5-50 alphanumeric characters
  - must be globally unique
- MANAGED_IDENTITY_NAME
  - 3-128 alphanumeric characters
  - must be unique in the resource group
- KEY_VAULT_NAME
  - 3-24 alphanumeric characters
  - must begin with a letter
  - must be globally unique

### resource group
```sh
az group create -n $RESOURCE_GROUP --location westus2
```

### managed identity
Create the managed identity:
```sh
az identity create -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME
```

Save its `clientId`, `id` (ARM URI), and `principalId` (object ID) for later:
```sh
export MANAGED_IDENTITY_CLIENT_ID=$(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME --query clientId -o tsv) \
       MANAGED_IDENTITY_ID=$(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME --query id -o tsv) \
       MANAGED_IDENTITY_PRINCIPAL_ID=$(az identity show -g $RESOURCE_GROUP -n $MANAGED_IDENTITY_NAME --query principalId -o tsv)
```

### Key Vault
Create the Vault:
```sh
az keyvault create -g $RESOURCE_GROUP -n $KEY_VAULT_NAME --sku standard
```

Add an access policy for the managed identity:
```sh
az keyvault set-policy -n $KEY_VAULT_NAME --object-id $MANAGED_IDENTITY_PRINCIPAL_ID --secret-permissions list
```

### container registry
```sh
az acr create -g $RESOURCE_GROUP -n $ACR_NAME --admin-enabled --sku basic
```

### Kubernetes
Deploy the cluster (this will take several minutes):
```sh
az aks create -g $RESOURCE_GROUP -n $AKS_NAME --generate-ssh-keys --node-count 1 --disable-rbac --attach-acr $ACR_NAME
```

Grant the cluster's service principal permission to use the managed identity:
```sh
az role assignment create --role "Managed Identity Operator" \
  --assignee $(az aks show -g $RESOURCE_GROUP -n $AKS_NAME --query servicePrincipalProfile.clientId -o tsv) \
  --scope $MANAGED_IDENTITY_ID
```

# build images
The test application must be packaged as a Docker image before deployment.
Test runs must include Python 2 and 3, so two images are required.

### authenticate to ACR
```sh
az acr login -n $ACR_NAME
```

### acquire the test code
```sh
git clone https://github.com/Azure/azure-sdk-for-python/ --branch master --single-branch --depth 1
```

The rest of this section assumes this working directory:
```sh
cd azure-sdk-for-python/sdk/identity/azure-identity/tests
```

### build images and push them to the container registry
Set environment variables:
```sh
export REPOSITORY=$ACR_NAME.azurecr.io IMAGE_NAME=test-pod-identity PYTHON_VERSION=2.7
```

Build an image:
```sh
docker build --no-cache --build-arg PYTHON_VERSION=$PYTHON_VERSION -t $REPOSITORY/$IMAGE_NAME:$PYTHON_VERSION ./managed-identity-live
```

Push it to ACR:
```sh
docker push $REPOSITORY/$IMAGE_NAME:$PYTHON_VERSION
```

Then set `PYTHON_VERSION` to the latest 3.x (3.8 at time of writing) and run the
above `docker build` and `docker push` commands again. (It's safe--and faster--
to omit `--no-cache` from `docker build` the second time.)

# run the test

### install kubectl
```sh
az aks install-cli
```

### authenticate kubectl and helm
```sh
az aks get-credentials -g $RESOURCE_GROUP -n $AKS_NAME
```

### install tiller
```sh
helm init --wait
```

### run the test script
Twice. Once with `PYTHON_VERSION=2.7`, once with `PYTHON_VERSION=3.x`
(replacing x with the latest Python 3 minor version):
```sh
python ./pod-identity/run-test.py \
 --client-id $MANAGED_IDENTITY_CLIENT_ID \
 --resource-id $MANAGED_IDENTITY_ID \
 --vault-url https://$KEY_VAULT_NAME.vault.azure.net \
 --repository $REPOSITORY \
 --image-name $IMAGE_NAME \
 --image-tag $PYTHON_VERSION
```

### delete Azure resources
```sh
az group delete -n $RESOURCE_GROUP -y --no-wait
```

**Comment by kurtzeborn** [comment]
@chlowel, it looks like you've got most of this figured out, what assistance do you need from the engineering system team?

**Comment by chlowell** [comment]
I want to replace all the manual steps above with an automated live test. I need a pipeline which builds the artifacts (in particular, Docker images), creates and destroys the Azure resources, runs the test script, and reports results.

**Comment by jianghaolu** [comment]
# For Java

Everything is the same prior to **Build Images**, with the ACR, AKS, Key Vault, managed identity created, and the managed identity is given secret permissions to the key vault.

## Build Images
The test application must be packaged as a Docker image before deployment.

### authenticate to ACR
Get credentials:
```sh
az acr credential show -n $ACR_NAME -o table
```

Authenticate with the "USERNAME" and either "PASSWORD":
```sh
az acr login -n $ACR_NAME -u <USERNAME> -p <PASSWORD>
```

### Create dockerfiles
Create a new directory, e.g. `pod-identity-test` and then create a Dockerfile underneath with content
```dockerfile
FROM alpine/git as clone
RUN git clone https://github.com/Azure/azure-sdk-for-java --single-branch --branch master --depth 1 /azure-sdk-for-java

FROM maven:3-jdk-8
COPY --from=clone /azure-sdk-for-java /azure-sdk-for-java
WORKDIR /azure-sdk-for-java
CMD [ "mvn", "test", "-Dtest=ManagedIdentityCredentialLiveTest#testIMDSEndpointWithUserAssigned*", "-pl", "sdk/e2e", "-f", "pom.client.xml", "-Dgpg.skip", "-am", "-DfailIfNoTests=false" ]
```

### build image and push to the container registry
```bash
export REPOSITORY=$ACR_NAME.azurecr.io IMAGE_NAME=test-pod-identity
docker build -t $REPOSITORY/$IMAGE_NAME ./pod-identity-test
docker push $REPOSITORY/$IMAGE_NAME
```

## Run the test

### install kubectl
```sh
az aks install-cli
```

### authenticate kubectl and helm
```sh
az aks get-credentials -g $RESOURCE_GROUP -n $AKS_NAME
```

### Create `aad-pod-identity` deployment on AKS
```sh
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment.yaml
```

### 3. Install the Azure Identity
Save this Kubernetes manifest to a file named `aadpodidentity.yaml`:

```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aad-pod-identity
spec:
  type: 0
  ResourceID: <value of $MANAGED_IDENTITY_ID>
  ClientID: <value of $AKS_CLIENT_ID>
```

Replace the placeholders with your user identity values. Save your changes to the file, then create the `AzureIdentity` resource in your cluster:

```shell
kubectl apply -f aadpodidentity.yaml
```

### Install the Azure Identity Binding

Save this Kubernetes manifest to a file named `aadpodidentitybinding.yaml`:

```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: demo1-azure-identity-binding
spec:
  AzureIdentity: aad-pod-identity
  Selector: aad-pod-identity-binding
```

Save your changes to the file, then create the `AzureIdentityBinding` resource in your cluster:

```shell
kubectl apply -f aadpodidentitybinding.yaml
```

### Start the test run jobs
Save this Kubernetes manifest to a file named `pod-identity-test.yaml`:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  labels:
    app: pod-identity-test
spec:
  backoffLimit: 12  # give up after this many attempts
  ttlSecondsAfterFinished: 3600  # delete the job and its sub-resources after this many seconds
  template:
    metadata:
      labels:
        app: pod-identity-test
        aadpodidbinding: aad-pod-identity-binding
    spec:
      restartPolicy: OnFailure  # ensure we have only one pod, whose logs reflect the last test run
      initContainers:
      - name: wait-for-imds  # wait until IMDS responds before running the test
        image: busybox:1.31
        command: ['sh', '-c', 'wget 169.254.169.254 -T 120']
      containers:
      - name: pod-identity-test
        image: <value of $ACR_NAME>.azurecr.io/test-pod-identity
        imagePullPolicy: Always
        env:
        - name: AZURE_VAULT_URL
          value: "https://<value of $KEY_VAULT_NAME>.vault.azure.net"
        - name: AZURE_CLIENT_ID
          value: "<value of $MANAGED_IDENTITY_CLIENT_ID>"
```

Finally, save your changes to the file, then start the test run for system assigned identity in your cluster:

```shell
kubectl apply -f pod-identity-test-user.yaml
```

Find out the name of the pod running through
```sh
$ kubectl get pod -l app=pod-identity-test
NAME         READY   STATUS      RESTARTS   AGE
test-8vx28   1/1     Running   0          22s
```

Tail the log of the test run
```sh
kubectl logs -f test-8vx28
```sh

If the tests succeed, console should print near the end
```sh
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.azure.endtoend.identity.ManagedIdentityCredentialLiveTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.55 s - in com.azure.endtoend.identity.ManagedIdentityCredentialLiveTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```
